#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=10

PROG=/usr/bin/frpc
CONF=/etc/frp/frpc.toml

start_service() {
	[ -x "$PROG" ] || return 0
	[ -f "$CONF" ] || return 0

	procd_open_instance frpc
	procd_set_param command "$PROG" -c "$CONF"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param file "$CONF"
	procd_close_instance
}

reload_service() {
	restart
}
