#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

start_service() {
	local enabled token
	config_load lst-signbox-lists-tgbot
	config_get enabled main enabled 1
	config_get token main token

	[ "$enabled" = "1" ] || return 0
	[ -n "$token" ] || {
		logger -t lst-signbox-lists-tgbot "token not set, skipping start"
		return 0
	}

	procd_open_instance
	procd_set_param command /usr/bin/lst-signbox-lists-tgbot
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger lst-signbox-lists-tgbot
}
